Collect-TV-20180201/src/objects/Local_Council_Form__c.object
<CustomObject>
    <description>Stores all of the TECHNET Local Council registration forms.</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <description>Name for the Local Council group.</description>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Local Council Form</label>
    <nameField>
        <label>Local Council Form Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETLocalCouncilCtrlTest.cls
/**
 * Created by yshao009 on 6/28/17.
 */
@IsTest
public with sharing class TNETLocalCouncilCtrlTest {
    static testMethod void testLocalCouncil(){
        TNETLocalCouncilCtrl.getInitData();
        Local_Council_Form__c lcf = new Local_Council_Form__c();
        lcf.Group_Name__c = 'test';
        TNETLocalCouncilCtrl.insertForm(lcf);
        List<String> idList = new List<String>();
        idList.add(lcf.Id);
        TNETLocalCouncilCtrl.DeleteRecord(idList);
    }
}