Collect-TV-20180201/src/objects/Tech_Net__c.object
<CustomObject>
    <fields>
        <fullName>TNET_Geo_Call_Status__c</fullName>
        <label>TNET Geo Call Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_City__c</fullName>
        <label>Website City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_State_Province__c</fullName>
        <label>Website State/Province</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website_Street__c</fullName>
        <label>Website Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Zip_Postal_Code__c</fullName>
        <label>Website Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TECH-NET</label>
    <nameField>
        <displayFormat>TECH-NET--{MM}{YYYY}-{0}</displayFormat>
        <label>TECH-NET Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETGeoTechNet.cls
/**
 * Created by yshao009 on 4/25/17.
 */

public with sharing class TNETGeoTechNet implements TNETIGeoAddress{
    private Tech_Net__c techShop;

    public TNETGeoTechNet() {

    }

    public void setSObject(SObject sobj){
        techShop = (Tech_Net__c)sobj;
    }

    public String getDisplayName() {
        return String.valueOf(this).substring(0,String.valueOf(this).indexOf(':')).replace(TNETGeoAddressUtil.OBJECT_PREFIX,'');
    }

    public String getAPIName() {
        return 'Tech_Net__c';
    }

    public String getLongitudeField(){
        return 'TNET_Geo_Location__Longitude__s';
    }

    public String getLatitudeField(){
        return 'TNET_Geo_Location__Latitude__s';
    }

    public String getStreetField(){
        return 'Website_Street__c';
    }

    public String getCityField(){
        return 'Website_City__c';
    }

    public String getStateField(){
        return 'Website_State_Province__c';
    }

    public String getPostalCodeField(){
        return 'Website_Zip_Postal_Code__c';
    }

    public String getCallStatusField(){
        return 'TNET_Geo_Call_Status__c';
    }

    public String getGeoAddress(){
        String address = '';

        if(techShop != null){
            address += (techShop.Website_Street__c == null ? '' : techShop.Website_Street__c) + ',';
            address += (techShop.Website_City__c == null ? '' : techShop.Website_City__c) + ',';
            address += (techShop.Website_State_Province__c == null ? '' : techShop.Website_State_Province__c) + ',';
            address += (techShop.Website_Zip_Postal_Code__c == null ? '' : techShop.Website_Zip_Postal_Code__c);
        }

        return address;
    }
}