Collect-TV-20180201/src/objects/Tech_Net__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Tech_Net</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>TECH-NET</label>
    <nameField>
        <displayFormat>TECH-NET--{MM}{YYYY}-{0}</displayFormat>
        <label>TECH-NET Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETRoadHazardFormTest.cls
/**
 * Created by sankur001 on 4/28/2017.
 */

@IsTest(SeeAllData = true)
private class TNETRoadHazardFormTest {
    static testMethod void testBehavior() {
        Contact dealer = TNET_TestUtil.testRoadHazard();
        String choice = 'Yes';
        String dealerName = 'AAP Dealer';

        Test.startTest();

        TNETRoadHazardFormCtrl.sendEmail(dealer,choice,dealerName);
        //TNETRoadHazardFormCtrl.getInitInfo();

        Test.stopTest();
    }
    static testMethod void testGetInitInfo() {
        List<Tech_Net__c> rsList = TNET_TestUtil.testTechNetDateCreated();
        User user = TNET_TestUtil.createCommunityUser(rsList[0].Account_Name__c);
        system.runAs(user) {
            TNETRoadHazardFormCtrl.getInitInfo();
        }
    }
}