Collect-TV-20180201/src/objects/Tech_Net__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Tech_Net</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Alignment_Service_or_Wheel_Alignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Alignment Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Available_on_Find_Your_Shop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available on Find Your Shop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collision_Repair__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Collision Repair</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Diagnostic_Service_Computer_Diagnosti__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Diagnostic Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Diesel_Specialist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Diesel Specialist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Electrical_Specialist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Electrical Specialist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Enrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>General_Repair__c</fullName>
        <defaultValue>false</defaultValue>
        <label>General Repair</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Heavy_Duty_Specialist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Heavy Duty Specialist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hybrid_Specialist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hybrid Specialist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Import_Specialist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Import Specialist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RV_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RV Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Shuttle_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shuttle Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Inspections__c</fullName>
        <defaultValue>false</defaultValue>
        <label>State Inspections</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Synchrony_Car_Care__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synchrony Car Care</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_36_36_Badge__c</fullName>
        <defaultValue>false</defaultValue>
        <label>36/36 Badge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_ASE_Certified_Badge__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ASE Certified Badge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_BBB_Badge__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BBB Badge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_Badges_Active__c</fullName>
        <formula>IF(TNET_36_36_Badge__c, 1, 0) +
IF(TNET_ASE_Certified_Badge__c, 1, 0) +
IF(TNET_BBB_Badge__c, 1, 0) +
IF(TNET_MAP_Badge__c, 1, 0) +
IF(TNET_RepairPal_Badge__c, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Badges Active</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TNET_Geo_Location__c</fullName>
        <label>TNET Geo Location</label>
        <scale>5</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>TNET_MAP_Badge__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MAP Badge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_More_Shop_Info__c</fullName>
        <label>More Shop Info</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TNET_RepairPal_Badge__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RepairPal Badge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_Service_Details__c</fullName>
        <label>Service Details</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tire_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tire Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Towing_Service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Towing Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Website_City__c</fullName>
        <label>Website City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Country__c</fullName>
        <label>Website Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Display_Name__c</fullName>
        <label>Website Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Primary_Phone__c</fullName>
        <label>​Website Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Website_State_Province__c</fullName>
        <label>Website State/Province</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website_Street__c</fullName>
        <label>Website Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Zip_Postal_Code__c</fullName>
        <label>Website Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website Address</label>
        <type>Url</type>
    </fields>
    <label>TECH-NET</label>
    <nameField>
        <displayFormat>TECH-NET--{MM}{YYYY}-{0}</displayFormat>
        <label>TECH-NET Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/objects/TNET_Section__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_Description__c</fullName>
        <label>Section Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Tab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TNET Tab</label>
        <referenceTo>TNET_Tab__c</referenceTo>
        <relationshipLabel>TNET Sections</relationshipLabel>
        <relationshipName>TNETS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Video_Url__c</fullName>
        <label>Video Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TNET Section</label>
    <nameField>
        <label>TNET Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/objects/TNET_Tab__c.object
<CustomObject>
    <fields>
        <fullName>Is_Hidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Hidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Navigation_Display_Name__c</fullName>
        <description>The name that will display on the navigation tab</description>
        <label>Navigation Display Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ParentTab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ParentTab</label>
        <referenceTo>TNET_Tab__c</referenceTo>
        <relationshipLabel>TNET Tabs</relationshipLabel>
        <relationshipName>TNET_Tabs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TNET_Tab_Type__c</fullName>
        <label>Tab Type</label>
        <picklist>
            <picklistValues>
                <fullName>Consumer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>TNET Tab</label>
    <nameField>
        <label>TNET Tabs Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETHomeCtrl.cls
/**
 * Created by yshao009 on 3/9/17.
 */

global without sharing class TNETHomeCtrl {
    @RemoteAction
    global static List<Tech_Net__c> findShopByKeyWord(Double latitude,Double longitude,Integer radius){




        String query = 'SELECT Website_Display_Name__c,Website_City__c,Website__c,' +
                'Website_Country__c, Website_Zip_Postal_Code__c,Website_State_Province__c,Website_Street__c,' +
                'Website_Primary_Phone__c,account_name__r.Email__c,Shuttle_Service__c,General_Repair__c,' +
                'Collision_Repair__c,Tire_Service__c,RV_Service__c,Towing_Service__c,Synchrony_Car_Care__c,' +
                'Import_Specialist__c ,Diesel_Specialist__c,Heavy_Duty_Specialist__c,' +
                'Alignment_Service_or_Wheel_Alignment__c,Hybrid_Specialist__c,Electrical_Specialist__c,' +
                'Diagnostic_Service_Computer_Diagnosti__c,State_Inspections__c,TNET_Geo_Location__Longitude__s,TNET_Geo_Location__Latitude__s,' +
                'TNET_36_36_Badge__c,TNET_ASE_Certified_Badge__c,TNET_RepairPal_Badge__c,TNET_Badges_Active__c,TNET_BBB_Badge__c,TNET_MAP_Badge__c,TNET_More_Shop_Info__c,TNET_Service_Details__c'+
                ' ,(SELECT id from Attachments ORDER BY CreatedDate DESC LIMIT 1)'+
                ' FROM Tech_Net__c ';
        String whereStr ='WHERE';
        whereStr = whereStr + ' Available_on_Find_Your_Shop__c = TRUE AND account_name__r.Tech_Net_Customer__c = TRUE';
        whereStr = whereStr + ' AND Enrollment_Status__c = \'Enrolled\' ';
        whereStr = whereStr + 'AND DISTANCE(TNET_Geo_Location__c,GEOLOCATION('+latitude+','+longitude+'),\'mi\') <'+radius;
        System.debug('query+whereStr:'+(query+whereStr));
        List<Tech_Net__c> techList = database.query(query+whereStr);

        return techList;
    }

    @AuraEnabled
    global static List<CollaborationGroup> getChatterGroups(){
        List<CollaborationGroupMember> groupMemberlist = [SELECT CollaborationGroupId FROM CollaborationGroupMember WHERE MemberId=:UserInfo.getUserId()];
        List<String> groupIdList = new List<String>();
        for(CollaborationGroupMember cgm:groupMemberlist){
            groupIdList.add(cgm.CollaborationGroupId);
        }

        List<CollaborationGroup > groupList = [SELECT Id,Name From CollaborationGroup where networkid=:Network.getNetworkId() AND id in:groupIdList];

        return groupList;
    }
    @AuraEnabled
    global static List<TNET_Tab__c> getConsumerTabs(){
        List<TNET_Tab__c> rs = [SELECT Id,Name,ParentTab__c,Is_Hidden__c,Navigation_Display_Name__c,
            (SELECT Order__c,Section_Description__c,Name,Video_Url__c FROM TNETS__r order by Order__c)
                FROM TNET_Tab__c WHERE TNET_Tab_Type__c ='Consumer' order by Order__c ];

        return rs;
    }

    @AuraEnabled
    global static List<TNET_Tab__c> getMemberTabs(){
        List<TNET_Tab__c> rs = [SELECT Id,Name,ParentTab__c,Is_Hidden__c,Navigation_Display_Name__c,
            (SELECT Order__c,Section_Description__c,Name,Video_Url__c FROM TNETS__r order by Order__c)
                FROM TNET_Tab__c WHERE TNET_Tab_Type__c ='Member' order by Order__c];

        return rs;
    }

    Global static void fakeTest(){
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;




    }

}