Collect-TV-20180201/src/objects/Tech_Net__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Tech_Net</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Enrolled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website_City__c</fullName>
        <label>Website City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Display_Name__c</fullName>
        <label>Website Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Primary_Phone__c</fullName>
        <label>​Website Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Website_State_Province__c</fullName>
        <label>Website State/Province</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Website_Street__c</fullName>
        <label>Website Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website_Zip_Postal_Code__c</fullName>
        <label>Website Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TECH-NET</label>
    <nameField>
        <displayFormat>TECH-NET--{MM}{YYYY}-{0}</displayFormat>
        <label>TECH-NET Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/objects/TECHNET_Item__c.object
<CustomObject>
    <description>Object to hold all of the Dell-Corning product records</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the TECHNET Item</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Item_Number__c</fullName>
        <description>Unique item number for the TECHNET Item</description>
        <label>Item Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Quantity__c</fullName>
        <description>The maximum quantity of the product that can be ordered at a time</description>
        <label>Max Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Per_Unit__c</fullName>
        <description>Unit cost of a TECHNET Item</description>
        <label>Price Per Unit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TNET_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>The type of unit that the product is sold in</description>
        <label>Unit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TECHNET Item</label>
    <nameField>
        <label>TECHNET Item Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/objects/TNET_Announcements__c.object
<CustomObject>
    <fields>
        <fullName>TNET_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TNET_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TNET_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TNET_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>TNET Announcement</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>TNET Announcements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/objects/TNET_Banner_Heading__c.object
<CustomObject>
    <fields>
        <fullName>TNET_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TNET_Heading_For_Banner__c</fullName>
        <label>Heading For Banner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>TNET_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TNET_Title__c</fullName>
        <label>Page Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>TNET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TNET Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TNET Tiles</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TNET_Video_URL__c</fullName>
        <label>Video URL</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <label>TNET Banner Heading</label>
    <nameField>
        <displayFormat>BH-{0000}</displayFormat>
        <label>Banner Heading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/objects/TNET_FAQ__c.object
<CustomObject>
    <fields>
        <fullName>TNET_FAQ_Number__c</fullName>
        <label>FAQ Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>TNET_FAQ_Title__c</fullName>
        <label>FAQ Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_FAQ_Type__c</fullName>
        <label>FAQ Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>TNET FAQ</label>
    <nameField>
        <displayFormat>TFAQ-{0000}</displayFormat>
        <label>TNET FAQ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/objects/TNET_Profile_Menu__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>path__c</fullName>
        <label>path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TNET Profile Menu</label>
    <nameField>
        <label>TNET Profile Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Date_in_Position__c</fullName>
        <label>Date in Position</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNET_TestUtil.cls
/**
 * Created by sankur001 on 4/18/2017.
 */
public with sharing class TNET_TestUtil {

    public static void TestHomeBannerHeading() {
        List<TNET_Banner_Heading__c> bannerList = new List<TNET_Banner_Heading__c>();
        TNET_Banner_Heading__c banner1 = new TNET_Banner_Heading__c();
        banner1.TNET_Title__c = 'Welcome to PwC1';
        banner1.TNET_Type__c = 'TNET';
        banner1.TNET_Order__c = 1;
        banner1.TNET_Heading_For_Banner__c = 'Hello PwC1';
        banner1.TNET_Description__c = 'This is a test banner for PwC1';
        banner1.TNET_Is_Active__c = true;
        bannerList.add(banner1);
        TNET_Banner_Heading__c banner2 = new TNET_Banner_Heading__c();
        banner2.TNET_Title__c = 'Welcome to PwC2';
        banner2.TNET_Type__c = 'TNET';
        banner2.TNET_Order__c = 2;
        banner2.TNET_Heading_For_Banner__c = 'Hello PwC2';
        banner2.TNET_Description__c = 'This is a test banner for PwC1';
        banner2.TNET_Is_Active__c = true;
        bannerList.add(banner2);
        TNET_Banner_Heading__c banner3 = new TNET_Banner_Heading__c();
        banner3.TNET_Title__c = 'Welcome to PwC1';
        banner3.TNET_Type__c = 'TNET';
        banner3.TNET_Order__c = 3;
        banner3.TNET_Heading_For_Banner__c = 'Hello PwC1';
        banner3.TNET_Description__c = 'This is a test banner for PwC1';
        banner3.TNET_Is_Active__c = true;
        bannerList.add(banner3);
        insert bannerList;

        Attachment att = new Attachment();
        att.Name = 'Test Attachment.JPG';
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        att.Body = bodyBlob;
        att.ContentType = 'image';
        att.ParentId = banner1.Id;
        insert att;

    }

    public static void TestPageBannerHeading() {
        List<TNET_Banner_Heading__c> bannerList = new List<TNET_Banner_Heading__c>();
        TNET_Banner_Heading__c banner1 = new TNET_Banner_Heading__c();
        banner1.TNET_Title__c = 'Nationwide Warranty';
        banner1.TNET_Type__c = 'TNET Page';
        banner1.TNET_Heading_For_Banner__c = 'Nationwide Warranty';
        banner1.TNET_Description__c = 'This is a test banner for PwC1';
        banner1.TNET_Is_Active__c = true;
        bannerList.add(banner1);
        insert bannerList;

        Attachment att = new Attachment();
        att.Name = 'Test Attachment.JPG';
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        att.Body = bodyBlob;
        att.ContentType = 'image';
        att.ParentId = banner1.Id;
        insert att;

    }

    public static void TestTileBannerHeading() {
        List<TNET_Banner_Heading__c> bannerList = new List<TNET_Banner_Heading__c>();
        TNET_Banner_Heading__c banner1 = new TNET_Banner_Heading__c();
        banner1.TNET_Title__c = 'Nationwide Warranty';
        banner1.TNET_Type__c = 'TNET Tiles';
        banner1.TNET_Heading_For_Banner__c = 'Nationwide Warranty';
        banner1.TNET_Description__c = 'This is a test banner for PwC1';
        banner1.TNET_Is_Active__c = true;
        banner1.TNET_Order__c = 1;
        bannerList.add(banner1);
        insert bannerList;

        Attachment att = new Attachment();
        att.Name = 'Test Attachment.JPG';
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        att.Body = bodyBlob;
        att.ContentType = 'image';
        att.ParentId = banner1.Id;
        insert att;

    }

    public static void TestFAQ() {
        List<TNET_FAQ__c> faqList = new List<TNET_FAQ__c>();
        TNET_FAQ__c faq = new TNET_FAQ__c();
        faq.TNET_FAQ_Title__c = 'Contact Us';
        //faq.TNET_FAQ_Number__c = '1';
        faq.TNET_FAQ_Type__c = 'Contact Us';
        faqList.add(faq);
        insert faqList;
    }

    public static void TestVVCarousel() {
        List<TNET_Banner_Heading__c> bannerList = new List<TNET_Banner_Heading__c>();
        TNET_Banner_Heading__c banner1 = new TNET_Banner_Heading__c();
        banner1.TNET_Title__c = 'Welcome to PwC1';
        banner1.TNET_Type__c = 'Virtual Vehicle';
        banner1.TNET_Image_URL__c='abc/com';
        banner1.TNET_Order__c = 1;
        banner1.TNET_Heading_For_Banner__c = 'Hello PwC1';
        banner1.TNET_Description__c = 'This is a test banner for PwC1';
        banner1.TNET_Is_Active__c = true;
        banner1.TNET_Video_URL__c='www.youtube.com';
        bannerList.add(banner1);
        insert bannerList;
    }

    public static void testTextCarousel() {
        List<TNET_Announcements__c> annList = new List<TNET_Announcements__c>();
        TNET_Announcements__c ann = new TNET_Announcements__c();
        ann.TNET_Description__c = 'Test annoncement';
        ann.TNET_Is_Active__c = true;
        ann.TNET_Start_Date__c=date.today().addDays(-20);
        ann.TNET_End_Date__c = date.today().addDays(20);
        ann.TNET_Order__c = 1;
        annList.add(ann);
        insert annList;
    }

    public static void testDocSearch() {
        List<Document> docList = new List<Document>();
        Document document;
        document = new Document();
        document.Body = Blob.valueOf('Some Text');
        document.ContentType = 'application/pdf';
        document.DeveloperName = 'my_document';
        document.IsPublic = true;
        document.Name = 'AAP';
        document.FolderId = [select id from folder where name = 'TECHNET Community Documents'].id;
        docList.add(document);
        insert docList;
    }

    public static Contact testRoadHazard()
    {
        Account act = new Account();
        act.Name = 'ABC';

        Contact cnt = new Contact();
        cnt.Account = act;
        cnt.LastName = 'ABC';
        cnt.Title='CEO';
        cnt.Email = 'anksriva@gmail.com';
        cnt.Phone = '1223232223';
        cnt.Fax= '2334343';
        cnt.OtherStreet = 'Test';
        cnt.OtherCity = 'Alabama';
        cnt.OtherState = 'Florida';
        cnt.OtherPostalCode = '323322';
        cnt.MailingStreet='Test';
        cnt.MailingCity = 'Alabama';
        cnt.MailingState = 'Florida';
        cnt.MailingPostalCode = '323322';

        return cnt;
    }

    public static List<Tech_Net__c>  testGeoBatch(){
        List<Account> accList = [SELECT ID FROM Account LIMIT 1];
        Tech_Net__c tech_net = new Tech_Net__c();
        tech_net.Website_Display_Name__c='ABC';
        tech_net.Website_Primary_Phone__c='123';
        tech_net.Website_City__c = 'CEDARTOWN';
        tech_net.Website_State_Province__c = 'GA';
        tech_net.Website_Street__c = '1007 EAST AVE';
        tech_net.Website_Zip_Postal_Code__c = '30125';
        tech_net.Email__c ='abc@def.com';
        tech_net.Account_Name__c = accList[0].Id;

        insert tech_net;
        tech_net.Enrollment_Status__c = System.Label.TNET_Form_Status_Enrolled;
        update tech_net;
        List<Tech_Net__c> rsList = new List<Tech_Net__c>();
        rsList.add(tech_net);
        return rsList;

    }

    public static List<Tech_Net__c>  testTechNetDateCreated(){
        List<Account> accList = [SELECT ID FROM Account LIMIT 2];
        Tech_Net__c tech_net = new Tech_Net__c();
        tech_net.Website_Primary_Phone__c='123';
        tech_net.Website_City__c = 'CEDARTOWN';
        tech_net.Website_State_Province__c = 'GA';
        tech_net.Website_Street__c = '1007 EAST AVE';
        tech_net.Website_Zip_Postal_Code__c = '30125';
        tech_net.Account_Name__c = accList[1].Id;

        insert tech_net;
        tech_net.Enrollment_Status__c = System.Label.TNET_Form_Status_Enrolled;
        update tech_net;
        List<Tech_Net__c> rsList = new List<Tech_Net__c>();
        rsList.add(tech_net);
        return rsList;

    }

    public static void testProfileMenu()
    {
        List<TNET_Profile_Menu__c> pmList = new List<TNET_Profile_Menu__c>();
        TNET_Profile_Menu__c act = new TNET_Profile_Menu__c();
        act.Name = 'My Profile';
        act.Order__c = 1;
        act.path__c ='My-Shop';
        pmList.add(act);

        TNET_Profile_Menu__c act1 = new TNET_Profile_Menu__c();
        act1.Name = 'Chatter Groups';
        act1.Order__c = 1;
        act1.path__c ='My-Shop';
        pmList.add(act1);

        insert pmList;
       // return act;
    }

    public static List<TNETDellCorningFormCtrl.CartItems> testCartItems(List<TECHNET_Item__c> tiList)
    {
        List<TNETDellCorningFormCtrl.CartItems> cartItems = new List<TNETDellCorningFormCtrl.CartItems>();
        TNETDellCorningFormCtrl.CartItems act = new TNETDellCorningFormCtrl.CartItems();
        act.Name = 'Floor Mat';
        act.cost = 49.99;
        act.quantity =1;
        act.id = tiList[0].id;
        act.orderAmount = 49.99;
        cartItems.add(act);

        TNETDellCorningFormCtrl.CartItems act1 = new TNETDellCorningFormCtrl.CartItems();
        act1.Name = 'Floor Mat';
        act1.cost = 59.99;
        act1.quantity =1;
        act1.id = tiList[1].id;
        act1.orderAmount = 59.99;
        cartItems.add(act1);

        return cartItems;
    }
    public static List<TNETDellCorningFormCtrl.StaticCling> testClings()
    {
        List<TNETDellCorningFormCtrl.StaticCling> cartItems = new List<TNETDellCorningFormCtrl.StaticCling>();
        TNETDellCorningFormCtrl.StaticCling act = new TNETDellCorningFormCtrl.StaticCling();
        act.itemName = 'test';
        act.isBusName = false;
        act.isAddress = false;
        act.isPhone = false;
        act.busName = 'isPhone';
        act.phone = 'isPhone';
        act.street = 'isPhone';
        act.city = 'isPhone';
        act.state = 'isPhone';
        act.zip = 'isPhone';

        cartItems.add(act);



        return cartItems;
    }
    public static User  createCommunityUser(String accId){
        List<Account> accList = [SELECT ID FROM Account LIMIT 1];
        Id p = [select id from profile where name='TECHNET Community User'].id;



        Contact con = new Contact(LastName ='testCon',AccountId = accId,Email='test123@noemail.com',Phone='123456789');
        insert con;
        User user = new User(alias = 'test123', email='test123@noemail.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                ContactId = con.Id,Date_in_Position__c=System.today(),
                timezonesidkey='America/Los_Angeles', username='tester@noemail.com');

        insert user;
        return user;

    }

    public static List<TECHNET_Item__c>  testItemMenu(String recType)
    {
        Id itemRecTypeId = Schema.SObjectType.TECHNET_Item__c.getRecordTypeInfosByName().get(recType).getRecordTypeId();

        List<TECHNET_Item__c> pmList = new List<TECHNET_Item__c>();
        TECHNET_Item__c act = new TECHNET_Item__c();
        act.Name = 'Floor Mat';
        act.Description__c = 'A mat to keep customer car clean during service';
        act.TNET_Is_Active__c =true;
        act.Item_Number__c = '123456';
        act.Max_Quantity__c = 10;
        act.Price_Per_Unit__c = 49.99;
        act.Unit_Type__c = '100 Mats';
        act.RecordTypeId = itemRecTypeId;
        pmList.add(act);

        TECHNET_Item__c act1 = new TECHNET_Item__c();
        act1.Name = 'Floor Mat1';
        act1.Description__c = 'A mat to keep customer car clean during service';
        act1.TNET_Is_Active__c =true;
        act1.Item_Number__c = '123457';
        act1.Max_Quantity__c = 12;
        act1.Price_Per_Unit__c = 59.99;
        act1.Unit_Type__c = '200 Mats';
        act1.RecordTypeId = itemRecTypeId;
        pmList.add(act1);

        insert pmList;
        return pmList;
    }
    
}