Collect-TV-20180201/src/objects/Tech_Net__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Tech_Net</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>TECH-NET</label>
    <nameField>
        <displayFormat>TECH-NET--{MM}{YYYY}-{0}</displayFormat>
        <label>TECH-NET Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETCareerModalCtrlTest.cls
/**
 * Created by yshao009 on 6/28/17.
 */

@IsTest(SeeAllData = true)
private class TNETCareerModalCtrlTest {
    static testMethod void testBehavior() {
        List<Tech_Net__c> rsList = TNET_TestUtil.testGeoBatch();
        User user = TNET_TestUtil.createCommunityUser(rsList[0].Account_Name__c);
        system.runAs(user) {
            Test.startTest();
            TNETCareerModalCtrl.CareerModalWrapper gm = TNETCareerModalCtrl.getMemberDetails();
            TNETCareerModalCtrl.sendEmail(JSON.serialize(gm));

            Test.stopTest();
        }
    }
}