Collect-TV-20180201/src/objects/Tech_Net__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Tech_Net</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>TECH-NET</label>
    <nameField>
        <displayFormat>TECH-NET--{MM}{YYYY}-{0}</displayFormat>
        <label>TECH-NET Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETMemberMyProfileCtrlTest.cls
/**
 * Created by yshao009 on 5/2/17.
 */
@IsTest(SeeAllData = true)
private class TNETMemberMyProfileCtrlTest {
    static testMethod void testProfile(){
        List<Tech_Net__c> rsList = TNET_TestUtil.testGeoBatch();
        User user = TNET_TestUtil.createCommunityUser(rsList[0].Account_Name__c);
        system.runAs(user) {
            TNETMemberMyProfileCtrl.getMemberDetails();
            TNETMemberMyProfileCtrl.updateMemberDetails(rsList[0]);
            TNETMemberMyProfileCtrl.getDetails();
            String attId = TNETMemberMyProfileCtrl.uploadImage('ffd8ffe000ffd9','png',rsList[0],null);
            TNETMemberMyProfileCtrl.uploadImage('ffd8ffe000ffd9','png',rsList[0],attId);
            TNETMemberMyProfileCtrl.uploadImage('ffd8ffe000ffd9','png',rsList[0],null);
            TNETMemberMyProfileCtrl.getMemberDetailsById(rsList[0].id);
        }

    }
}