Collect-TV-20180201/src/objects/TNET_Banner_Heading__c.object
<CustomObject>
    <fields>
        <fullName>TNET_Heading_For_Banner__c</fullName>
        <label>Heading For Banner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>TNET_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TNET_Title__c</fullName>
        <label>Page Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>TNET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TNET Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TNET Tiles</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TNET_Video_URL__c</fullName>
        <label>Video URL</label>
        <length>20000</length>
        <type>LongTextArea</type>
    </fields>
    <label>TNET Banner Heading</label>
    <nameField>
        <displayFormat>BH-{0000}</displayFormat>
        <label>Banner Heading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETVirtualVehicleCtrl.cls
public without sharing class TNETVirtualVehicleCtrl {
    
    @AuraEnabled
    public static List<BannerHeadingWrapper> getBannerHeadings(String type) {
        Set<Id> bannerHeadingIdSet = new Set<Id>();
        List<TNET_Banner_Heading__c> bannerHeadingList = [
            SELECT  TNET_Title__c,
            TNET_Heading_For_Banner__c,
            TNET_Image_URL__c,
            TNET_Video_URL__c
            FROM    TNET_Banner_Heading__c
            WHERE   TNET_Is_Active__c = true
            AND     TNET_Type__c =:type
            ORDER BY TNET_Order__c ASC];//'Virtual Vehicle'
        
        for (TNET_Banner_Heading__c bh : bannerHeadingList) {
            bannerHeadingIdSet.add(bh.Id);
        }
        System.debug(LoggingLevel.INFO, '*** bannerHeadingIdSet: ' + bannerHeadingIdSet);
        
        Map<Id, String> bannerHeadingIdImageMap = new Map<Id, String>();
        for (TNET_Banner_Heading__c a : bannerHeadingList) {
            //     if (TNETUtil.isAvailableImage(a.Name)) {
            //         if (!bannerHeadingIdImageMap.containsKey(a.ParentId)) {
            bannerHeadingIdImageMap.put(a.Id, a.TNET_Image_URL__c);
            // }
            //  }
        }
        System.debug(LoggingLevel.INFO, '*** bannerHeadingIdImageMap: ' + bannerHeadingIdImageMap);
        
        List<BannerHeadingWrapper> BannerHeadingWrapperList = new List<BannerHeadingWrapper>();
        for (TNET_Banner_Heading__c bh : bannerHeadingList) {
            String bannerImage = bannerHeadingIdImageMap.get(bh.Id);
            System.debug(LoggingLevel.INFO, '*** bannerImage: ' + bannerImage);
            if(bannerImage != null){
                BannerHeadingWrapper bhw = new BannerHeadingWrapper();
                bhw.bannerHeading = bh;
                bhw.bannerImage = bannerImage;
                if(bh.TNET_Video_URL__c !=null) bhw.bannerVideo = bh.TNET_Video_URL__c;
                BannerHeadingWrapperList.add(bhw);
            }
        }
        System.debug(LoggingLevel.INFO, '*** BannerHeadingWrapperList: ' + BannerHeadingWrapperList);
        return BannerHeadingWrapperList;
    }
    
  /*  @AuraEnabled
    public static String getVideoURL(String bannerImage) {
        List<BannerHeadingWrapper> BannerHeadingWrapperList = getBannerHeadings();
        String videoURL =null;
        for (BannerHeadingWrapper bh : BannerHeadingWrapperList) {
            System.debug(LoggingLevel.INFO, '*** bannerImage: ' + bannerImage);
            if(bannerImage != null && bh.bannerImage == bannerImage)
            {
                videoURL = bh.bannerVideo;
            }      
        }
        return videoURL;
    } */
    
    public class BannerHeadingWrapper {
        @AuraEnabled
        public TNET_Banner_Heading__c bannerHeading {get; set;}
        @AuraEnabled
        public String bannerImage {get; set;}
        @AuraEnabled
        public String bannerVideo {get; set;}
    }
}