Collect-TV-20180201/src/objects/TNET_Banner_Heading__c.object
<CustomObject>
    <fields>
        <fullName>TNET_Banner_Title__c</fullName>
        <label>Banner Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_Carousel_Image__c</fullName>
        <label>Carousel Image</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TNET_Heading_For_Banner__c</fullName>
        <label>Heading For Banner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TNET_Title__c</fullName>
        <label>Page Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TNET_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>TNET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TNET Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TNET Tiles</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TNET_URL__c</fullName>
        <label>URL</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>TNET Banner Heading</label>
    <nameField>
        <displayFormat>BH-{0000}</displayFormat>
        <label>Banner Heading Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETBannerHeadingCtrl.cls
public with sharing class TNETBannerHeadingCtrl {

    @AuraEnabled
    public static List<BannerHeadingWrapper> getBannerHeadings() {
        Set<Id> bannerHeadingIdSet = new Set<Id>();
        List<TNET_Banner_Heading__c> bannerHeadingList = [
            SELECT  TNET_Title__c,
                    TNET_Heading_For_Banner__c,
                    TNET_Description__c,
            		TNET_URL__c,
                    TNET_Carousel_Image__c
            FROM    TNET_Banner_Heading__c
            WHERE   TNET_Is_Active__c = true
            AND     TNET_Type__c = 'TNET'
            ORDER BY TNET_Order__c ASC ];

        for (TNET_Banner_Heading__c bh : bannerHeadingList) {
            bannerHeadingIdSet.add(bh.Id);
        }
        System.debug(LoggingLevel.INFO, '*** bannerHeadingIdSet: ' + bannerHeadingIdSet);

        Map<Id, String> bannerHeadingIdImageMap = new Map<Id, String>();
        for (Attachment a : [
                SELECT  Name,
                        ParentId
                FROM    Attachment
                WHERE   ParentId IN :bannerHeadingIdSet
                ORDER BY LastModifiedDate DESC]) {
            if (TNETUtil.isAvailableImage(a.Name)) {
                if (!bannerHeadingIdImageMap.containsKey(a.ParentId)) {
                 //      !URLFOR($Action.Attachment.Download
                       bannerHeadingIdImageMap.put(a.ParentId, Site.getBaseUrl() + '/servlet/servlet.FileDownload?file=' + a.Id);
                 //      bannerHeadingIdImageMap.put(a.ParentId, Site.getBaseUrl() + '/servlet/servlet.FileDownload?file=' + a.Id);
                }
            }
        }
        System.debug(LoggingLevel.INFO, '*** bannerHeadingIdImageMap: ' + bannerHeadingIdImageMap);

        List<BannerHeadingWrapper> BannerHeadingWrapperList = new List<BannerHeadingWrapper>();
        for (TNET_Banner_Heading__c bh : bannerHeadingList) {
            String bannerImage = bannerHeadingIdImageMap.get(bh.Id);
           // String bannerImage = getResourceURL(bh.TNET_Carousel_Image__c);
            System.debug(LoggingLevel.INFO, '*** bannerImage: ' + bannerImage);
            if(bannerImage != null){
                BannerHeadingWrapper bhw = new BannerHeadingWrapper();
                bhw.bannerHeading = bh;
                bhw.bannerImage = bannerImage;
                BannerHeadingWrapperList.add(bhw);
            }
        }
        System.debug(LoggingLevel.INFO, '*** BannerHeadingWrapperList: ' + BannerHeadingWrapperList);
        return BannerHeadingWrapperList;
    }
    
        @AuraEnabled
    public static List<BannerHeadingWrapper> getPageBanners(String tabName) {//String tabName
        Set<Id> bannerHeadingIdSet = new Set<Id>();
        String tab = tabName.replace('-', ' ');
        List<TNET_Banner_Heading__c> bannerHeadingList = [
            SELECT  TNET_Title__c,
                    TNET_Banner_Title__c
            FROM    TNET_Banner_Heading__c
            WHERE   TNET_Is_Active__c = true
            AND     TNET_Type__c = 'TNET Page'
            AND		TNET_Title__c =:tab];

        for (TNET_Banner_Heading__c bh : bannerHeadingList) {
            bannerHeadingIdSet.add(bh.Id);
        }
        System.debug(LoggingLevel.INFO, '*** bannerHeadingIdSet: ' + bannerHeadingIdSet);

        Map<Id, String> bannerHeadingIdImageMap = new Map<Id, String>();
        for (Attachment a : [
                SELECT  Name,
                        ParentId
                FROM    Attachment
                WHERE   ParentId IN :bannerHeadingIdSet
                ORDER BY LastModifiedDate DESC]) {
            if (TNETUtil.isAvailableImage(a.Name)) {
                if (!bannerHeadingIdImageMap.containsKey(a.ParentId)) {
                 //      !URLFOR($Action.Attachment.Download
                       bannerHeadingIdImageMap.put(a.ParentId, Site.getBaseUrl() + '/servlet/servlet.FileDownload?file=' + a.Id);
                 //      bannerHeadingIdImageMap.put(a.ParentId, Site.getBaseUrl() + '/servlet/servlet.FileDownload?file=' + a.Id);
                }
            }
        }
        System.debug(LoggingLevel.INFO, '*** bannerHeadingIdImageMap: ' + bannerHeadingIdImageMap);

        List<BannerHeadingWrapper> BannerHeadingWrapperList = new List<BannerHeadingWrapper>();
        for (TNET_Banner_Heading__c bh : bannerHeadingList) {
            String bannerImage = bannerHeadingIdImageMap.get(bh.Id);
            System.debug(LoggingLevel.INFO, '*** bannerImage: ' + bannerImage);
            if(bannerImage != null){
                BannerHeadingWrapper bhw = new BannerHeadingWrapper();
                bhw.bannerHeading = bh;
                bhw.bannerImage = bannerImage;
                BannerHeadingWrapperList.add(bhw);
            }
        }
        System.debug(LoggingLevel.INFO, '*** BannerHeadingWrapperList: ' + BannerHeadingWrapperList);
        return BannerHeadingWrapperList;
    }
    @AuraEnabled
	public static List<BannerHeadingWrapper> getBannerHeadingsForTileCmp() {
        Set<Id> bannerHeadingIdSet = new Set<Id>();
        List<TNET_Banner_Heading__c> bannerHeadingList = [
                SELECT  TNET_Title__c,
                        TNET_Heading_For_Banner__c,
                        TNET_Description__c,
                        TNET_URL__c
                FROM    TNET_Banner_Heading__c
                WHERE   TNET_Is_Active__c = true
                AND     TNET_Type__c = 'TNET Tiles'
                ORDER BY TNET_Order__c ASC ];

        for (TNET_Banner_Heading__c bh : bannerHeadingList) {
            bannerHeadingIdSet.add(bh.Id);
        }
        System.debug(LoggingLevel.INFO, '*** bannerHeadingIdSet: ' + bannerHeadingIdSet);

        Map<Id, String> bannerHeadingIdImageMap = new Map<Id, String>();
        for (Attachment a : [
                SELECT  Name,
                        ParentId
                FROM    Attachment
                WHERE   ParentId IN :bannerHeadingIdSet
                ORDER BY LastModifiedDate DESC]) {
            if (TNETUtil.isAvailableImage(a.Name)) {
                if (!bannerHeadingIdImageMap.containsKey(a.ParentId)) {
                    //      !URLFOR($Action.Attachment.Download
                    bannerHeadingIdImageMap.put(a.ParentId, Site.getBaseUrl() + '/servlet/servlet.FileDownload?file=' + a.Id);
                    //      bannerHeadingIdImageMap.put(a.ParentId, Site.getBaseUrl() + '/servlet/servlet.FileDownload?file=' + a.Id);
                }
            }
        }
        System.debug(LoggingLevel.INFO, '*** bannerHeadingIdImageMap: ' + bannerHeadingIdImageMap);

        List<BannerHeadingWrapper> BannerHeadingWrapperList = new List<BannerHeadingWrapper>();
        for (TNET_Banner_Heading__c bh : bannerHeadingList) {
            String bannerImage = bannerHeadingIdImageMap.get(bh.Id);
            System.debug(LoggingLevel.INFO, '*** bannerImage: ' + bannerImage);
            if(bannerImage != null){
                BannerHeadingWrapper bhw = new BannerHeadingWrapper();
                bhw.bannerHeading = bh;
                bhw.bannerImage = bannerImage;
                BannerHeadingWrapperList.add(bhw);
            }
        }
        System.debug(LoggingLevel.INFO, '*** BannerHeadingWrapperList: ' + BannerHeadingWrapperList);
        return BannerHeadingWrapperList;
    }
    public class BannerHeadingWrapper {
        @AuraEnabled
        public TNET_Banner_Heading__c bannerHeading {get; set;}
        @AuraEnabled
        public String bannerImage {get; set;}
    }
/*
    public static String getResourceURL(String resourceName){
        List<StaticResource> resourceList= [SELECT Name, NamespacePrefix, SystemModStamp FROM StaticResource WHERE Name =:resourceName];
        if(resourceList.size() == 1){
            String namespace = resourceList[0].NamespacePrefix;
            return '/members/resource/' + resourceList[0].SystemModStamp.getTime() + '/' + resourceName;
        }
        else return '';
    } */
}