Collect-TV-20180201/src/objects/TNET_Announcements__c.object
<CustomObject>
    <fields>
        <fullName>TNET_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TNET_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TNET_Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TNET_Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TNET_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>TNET Announcement</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>TNET Announcements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Collect-TV-20180201/src/classes/TNETTextCtrl.cls
/**
 * Created by sankur001 on 4/5/2017.
 */

public with sharing class TNETTextCtrl {

    @AuraEnabled
    public static List<TNET_Announcements__c> getBannerHeadings() {
        Set<Id> bannerHeadingIdSet = new Set<Id>();
        //Date stDate = date.today().addDays(-30);
        //Date endDate = date.today().addDays(30);
        List<TNET_Announcements__c> bannerHeadingList = [
                SELECT TNET_Description__c
                FROM TNET_Announcements__c
                WHERE TNET_Is_Active__c = true
                AND TNET_Start_Date__c <= today
                AND TNET_End_Date__c >= today
                ORDER BY TNET_Order__c ASC
        ];

        return bannerHeadingList;
    }
}